/**
 * Embedded panchang data for all years.
 * This file imports all panchang JSON files and exports them as a single object.
 * This avoids dynamic import issues in bundled code.
 *
 * Generated by: pnpm generate:panchang
 * Source: @ishubhamx/panchangam-js (astronomy-engine, Swiss Ephemeris accuracy)
 * Location: Kathmandu, Nepal (27.7172°N, 85.3240°E, UTC+5:45)
 */

import data2080 from './2080.json' assert { type: 'json' }
import data2081 from './2081.json' assert { type: 'json' }
import data2082 from './2082.json' assert { type: 'json' }
import data2083 from './2083.json' assert { type: 'json' }
import data2084 from './2084.json' assert { type: 'json' }
import data2085 from './2085.json' assert { type: 'json' }
import data2086 from './2086.json' assert { type: 'json' }
import data2087 from './2087.json' assert { type: 'json' }
import data2088 from './2088.json' assert { type: 'json' }
import data2089 from './2089.json' assert { type: 'json' }
import data2090 from './2090.json' assert { type: 'json' }

export const PANCHANG_DATA: Record<number, typeof data2082> = {
  2080: data2080,
  2081: data2081,
  2082: data2082,
  2083: data2083,
  2084: data2084,
  2085: data2085,
  2086: data2086,
  2087: data2087,
  2088: data2088,
  2089: data2089,
  2090: data2090,
}

export type { PanchangEntry } from './schema.js'
